routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');
});

/**
 * Backend routes
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');

    //Users
    Route::get('users', 'UserController@index')->name('users');
    Route::get('users/{user}', 'UserController@show')->name('users.show');
    //Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::put('users/{user}', 'UserController@update')->name('users.update');
    Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');

    //User Profile
    Route::get('profiles', 'UserProfileController@index')->name('profiles');
    Route::get('profiles/{profile}', 'UserProfileController@show')->name('profiles.show');
    Route::get('profiles/{profile}/edit', 'UserProfileController@edit')->name('profiles.edit');
    Route::put('profiles/{profile}', 'UserProfileController@update')->name('profiles.update');
    Route::get('profiles/{profile}/delete', 'UserProfileController@destroy')->name('profiles.destroy');

    //Posts
    Route::get('posts', 'PostController@index')->name('posts');
    Route::get('posts/{post}', 'PostController@show')->name('posts.show');
    Route::get('posts/{post}/delete', 'PostController@destroy')->name('posts.destroy');

    //Posts Activity
    Route::get('activities', 'PostActivityController@index')->name('postactivities');
    Route::get('activities/{actvity}', 'PostActivityController@show')->name('postactivities.show');
    Route::get('activities/{actvity}/delete', 'PostActivityController@destroy')->name('postactivities.destroy');

    //Comments
    Route::get('comments', 'CommentController@index')->name('comments');
    Route::get('comments/{comment}', 'CommentController@show')->name('comments.show');
    Route::get('comments/{comment}/delete', 'CommentController@destroy')->name('comments.destroy');

    //Comments Activity
    Route::get('comment/activities', 'UserController@index')->name('commentsactivities');

    // Agama
    Route::get('agamas', 'AgamaController@index')->name('agamas');
    Route::get('agamas/{agama}', 'AgamaController@show')->name('agamas.show');
    Route::get('agamas/{agama}/edit', 'AgamaController@edit')->name('agamas.edit');
    Route::put('agamas/{agama}', 'AgamaController@update')->name('agamas.update');
    Route::get('agamas/{agama}/delete', 'AgamaController@destroy')->name('agamas.destroy');
});


Route::get('/', 'Auth\LoginController@showLoginForm');

resources/views/admin/sections/footer.blade.php
<div class="pull-right">
    &copy; {{ date('Y') }} {{ config('app.name') }}. {{ __('views.backend.section.footer.copyright') }}
</div>
<div class="clearfix"></div>

resources/views/admin/sections/header.blade.php
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                       aria-expanded="false">
                        <img src="{{ auth()->user()->avatar }}" alt="">{{ auth()->user()->name }}
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li>
                            <a href="{{ route('logout') }}">
                                <i class="fa fa-sign-out pull-right"></i> {{ __('views.backend.section.header.menu_0') }}
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>

resources/views/admin/sections/navigation.blade.php
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <!-- menu profile quick info -->
        <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><span>Owhlo Admin</span></a>
        </div>
        <!-- /menu profile quick info -->

        <br/>

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>{{ __('views.backend.section.navigation.sub_header_1') }}</h3>
                <ul class="nav side-menu">
                    <li>
                        <a href="{{ route('admin.dashboard') }}">
                            <i class="fa fa-dashboard" aria-hidden="true"></i>
                            Dashboard
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('admin.profiles') }}">
                            <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                            User Profiles
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('admin.posts') }}">
                            <i class="fa fa-tags" aria-hidden="true"></i>
                            Posts
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('admin.users') }}">
                            <i class="fa fa-user-o" aria-hidden="true"></i>
                            Admin Users
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('admin.agamas') }}">
                            <i class="fa fa-user-o" aria-hidden="true"></i>
                            Agama
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /sidebar menu -->
    </div>
</div>