routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');
});

/**
 * Backend routes
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');

    //Users
    Route::get('users', 'UserController@index')->name('users');
    Route::get('users/{user}', 'UserController@show')->name('users.show');
    //Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::put('users/{user}', 'UserController@update')->name('users.update');
    Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');

    //User Profile
    Route::get('profiles', 'UserProfileController@index')->name('profiles');
    Route::get('profiles/{profile}', 'UserProfileController@show')->name('profiles.show');
    Route::get('profiles/{profile}/edit', 'UserProfileController@edit')->name('profiles.edit');
    Route::put('profiles/{profile}', 'UserProfileController@update')->name('profiles.update');
    Route::get('profiles/{profile}/delete', 'UserProfileController@destroy')->name('profiles.destroy');

    //Posts
    Route::get('posts', 'PostController@index')->name('posts');
    Route::get('posts/{post}', 'PostController@show')->name('posts.show');
    Route::get('posts/{post}/delete', 'PostController@destroy')->name('posts.destroy');

    //Posts Activity
    Route::get('activities', 'PostActivityController@index')->name('postactivities');
    Route::get('activities/{actvity}', 'PostActivityController@show')->name('postactivities.show');
    Route::get('activities/{actvity}/delete', 'PostActivityController@destroy')->name('postactivities.destroy');

    //Comments
    Route::get('comments', 'CommentController@index')->name('comments');
    Route::get('comments/{comment}', 'CommentController@show')->name('comments.show');
    Route::get('comments/{comment}/delete', 'CommentController@destroy')->name('comments.destroy');

    //Comments Activity
    Route::get('comment/activities', 'UserController@index')->name('commentsactivities');

    // Agama
    Route::get('agamas', 'AgamaController@index')->name('agamas');
    Route::get('agamas/{agama}', 'AgamaController@show')->name('agamas.show');
    Route::get('agamas/{agama}/edit', 'AgamaController@edit')->name('agamas.edit');
    Route::put('agamas/{agama}', 'AgamaController@update')->name('agamas.update');
    Route::get('agamas/{agama}/delete', 'AgamaController@destroy')->name('agamas.destroy');
});


Route::get('/', 'Auth\LoginController@showLoginForm');

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class Comment extends Model
{
    use Sortable;

    public function getUserProfileIdAttribute($value)
    {
	return UserProfile::select(['id', 'name','gender', 'image'])->find($value);
    }

    public function comment_activities()
    {
        return $this->hasMany('App\Models\CommentActivity');
    }
}

app/Http/Controllers/Admin/CommentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Auth\Role\Role;
use App\Models\Auth\User\User;
use App\Models\Comment;
use App\Models\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use Validator;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $comments = Comment::sortable(['created_at' => 'desc']);
        if($request->post_id) {
            $comments = $comments->where('post_id', $request->post_id);
        }
        return view('admin.comments.index', ['comments' => $comments->paginate()]);
    }

    /**
     * Display the specified resource.
     *
     * @param Post $post
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Comment $comment)
    {
        return view('admin.comments.show', ['comment' => $comment]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return redirect(route('admin.comments'));
    }
}

app/Http/Controllers/Api/CommentController.php
<?php

namespace App\Http\Controllers\Api;

use App\Helpers\PostHelper;
use App\Http\Requests\CreateCommentRequest;
use App\Models\Comment;
use App\Models\CommentActivity;
use App\Models\Post;
use App\Models\UserProfile;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class CommentController extends Controller
{
    public function index($post) {
        $user = Auth::user();
        $profile = UserProfile::where('user_id', $user->id)->firstOrFail();

        $countsQuery = [
            'comment_activities as like_count' => function ($query) {
                $query->where('type', config('constants.COMMENT_ACTIVITY_LIKE'));
            },
            'comment_activities as dislike_count' => function ($query) {
                $query->where('type', config('constants.COMMENT_ACTIVITY_DISLIKE'));
            },
            'comment_activities as liked' => function ($query) use ($profile) {
                $query->where('user_profile_id', $profile->id)
                    ->where('type', config('constants.COMMENT_ACTIVITY_LIKE'));
            },
            'comment_activities as disliked' => function ($query) use ($profile) {
                $query->where('user_profile_id', $profile->id)
                    ->where('type', config('constants.COMMENT_ACTIVITY_DISLIKE'));
            }
        ];

        $comments = Comment::where('post_id', $post)->orderBy('created_at', 'desc')->withCount($countsQuery)->paginate(config('constants.paginate_per_page'));
        return response()->json($comments);
    }

    public function like(Comment $comment) {
        $status = $this->likeDislikeComment($comment, config('constants.COMMENT_ACTIVITY_LIKE'));
        return response()->json(array("id" => $comment->id, "status" => $status), 200);
    }

    public function dislike(Comment $comment) {
        $status = $this->likeDislikeComment($comment, config('constants.COMMENT_ACTIVITY_DISLIKE'));
        return response()->json(array("id" => $comment->id, "status" => $status), 200);
    }

    public function store(Post $post, CreateCommentRequest $request) {
        $user = Auth::user();
        $profile = UserProfile::where('user_id', $user->id)->first();
        $comment = new Comment();
        $comment->text = $request->text;
        $comment->post_id = $post->id;
        $comment->user_profile_id = $profile->id;
        $comment->save();

 	if($post->user_profile_id->user_profile_id == $profile->id) { return 1; }
	
        PostHelper::createPostActivity($profile, $post->id, config('constants.POST_ACTIVITY_COMMENT'));

        return response()->json(Comment::find($comment->id));
    }

    public function destroy(Comment $comment) {
        $deleted = $comment->delete();
        $status = $deleted ? 200 : 400;
        return response()->json(null, $status);
    }

    private function likeDislikeComment($comment, $type)
    {
        $user = Auth::user();
        $profile = UserProfile::where('user_id', $user->id)->firstOrFail();

        $previousActivity = CommentActivity::where('user_profile_id', $profile->id)
            ->where('comment_id', $comment->id)
            ->whereIn('type', array(config('constants.COMMENT_ACTIVITY_LIKE'), config('constants.COMMENT_ACTIVITY_DISLIKE')))
            ->first();

        if ($previousActivity) {
            $previousActivity->delete();

            if ($previousActivity->type == $type) {
                return -1;
            }
        }
	
#	if($comment->user_profile_id->user_profile_id == $profile->id) { return 1; }

        PostHelper::createCommentActivity($profile, $comment->id, $type);
        return 1;
    }
}

resources/views/admin/comments/index.blade.php
@extends('admin.layouts.admin')

@section('title','Comments')

@section('content')
    <div class="row">
        <table class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0"
               width="100%">
            <thead>
            <tr>
                <th>Post ID</th>
                <th>Posted By</th>
                <th>Text</th>
                <th>Created At</th>
                <th>Update At</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($comments as $comment)
                <tr>
                    <td>{{ $comment->post_id }}</td>
                    <td><a href="{{ route('admin.profiles.show', [$comment->user_profile_id->id]  ) }}">{{ $comment->user_profile_id->name }}</a></td>
                    <td>{{ str_limit($comment->text, $limit = 20, $end = '...') }}</td>
                    <td>{{ $comment->created_at }}</td>
                    <td>{{ $comment->updated_at }}</td>
                    <td>
                        <a class="btn btn-xs btn-primary" href="{{ route('admin.comments.show', [$comment->id]) }}"
                           data-toggle="tooltip" data-placement="top" data-title="View">
                            <i class="fa fa-eye"></i>
                        </a>
                        <a class="btn btn-xs btn-danger" href="{{ route('admin.comments.destroy', [$comment->id]) }}"
                           data-toggle="tooltip" data-placement="top" data-title="Delete">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="pull-right">
            {{ $comments->links() }}
        </div>
    </div>
@endsection

resources/views/admin/comments/show.blade.php
@extends('admin.layouts.admin')

@section('title', 'Comment')

@section('content')
    <div class="row">
        <table class="table table-striped table-hover">
            <tbody>
            <tr>
                <th>ID</th>
                <td>{{ $comment->id }}</td>
            </tr>

            <tr>
                <th>Text</th>
                <td>{{ $comment->text }}</td>
            </tr>

            <tr>
                <th>User</th>
                <td><a href="{{ route('admin.posts.show', [$comment->user_profile_id->id]  ) }}">{{ $comment->user_profile_id->name }}</a></td>
            </tr>
            
            <tr>
                <th>Created At</th>
                <td>{{ $comment->created_at }} ({{ $comment->created_at->diffForHumans() }})</td>
            </tr>

            <tr>
                <th>Updated At</th>
                <td>{{ $comment->updated_at }} ({{ $comment->updated_at->diffForHumans() }})</td>
            </tr>
            </tbody>
        </table>
    </div>
    <a class="btn btn-danger" href="{{ route('admin.comments.destroy', [$comment->id]) }}"
       data-toggle="tooltip" data-placement="top" data-title="Delete">Delete</a>
    <a class="btn btn-success" href="{{ route('admin.commentsactivities', ["comment_id" => $comment->id]) }}"
       data-toggle="tooltip" data-placement="top" data-title="Delete">View Activities</a>
    <a class="btn btn-primary" href="{{ URL::previous() }}">Back</a>
@endsection