routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');
});

/**
 * Backend routes
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');

    //Users
    Route::get('users', 'UserController@index')->name('users');
    Route::get('users/{user}', 'UserController@show')->name('users.show');
    //Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::put('users/{user}', 'UserController@update')->name('users.update');
    Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');

    //User Profile
    Route::get('profiles', 'UserProfileController@index')->name('profiles');
    Route::get('profiles/{profile}', 'UserProfileController@show')->name('profiles.show');
    Route::get('profiles/{profile}/edit', 'UserProfileController@edit')->name('profiles.edit');
    Route::put('profiles/{profile}', 'UserProfileController@update')->name('profiles.update');
    Route::get('profiles/{profile}/delete', 'UserProfileController@destroy')->name('profiles.destroy');

    //Posts
    Route::get('posts', 'PostController@index')->name('posts');
    Route::get('posts/{post}', 'PostController@show')->name('posts.show');
    Route::get('posts/{post}/delete', 'PostController@destroy')->name('posts.destroy');

    //Posts Activity
    Route::get('activities', 'PostActivityController@index')->name('postactivities');
    Route::get('activities/{actvity}', 'PostActivityController@show')->name('postactivities.show');
    Route::get('activities/{actvity}/delete', 'PostActivityController@destroy')->name('postactivities.destroy');

    //Comments
    Route::get('comments', 'CommentController@index')->name('comments');
    Route::get('comments/{comment}', 'CommentController@show')->name('comments.show');
    Route::get('comments/{comment}/delete', 'CommentController@destroy')->name('comments.destroy');

    //Comments Activity
    Route::get('comment/activities', 'UserController@index')->name('commentsactivities');

    // Agama
    Route::get('agamas', 'AgamaController@index')->name('agamas');
    Route::get('agamas/{agama}', 'AgamaController@show')->name('agamas.show');
    Route::get('agamas/{agama}/edit', 'AgamaController@edit')->name('agamas.edit');
    Route::put('agamas/{agama}', 'AgamaController@update')->name('agamas.update');
    Route::get('agamas/{agama}/delete', 'AgamaController@destroy')->name('agamas.destroy');
});


Route::get('/', 'Auth\LoginController@showLoginForm');

app/Models/UserProfile.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;
use Overtrue\LaravelFollow\Traits\CanFollow;
use Overtrue\LaravelFollow\Traits\CanBeFollowed;

class UserProfile extends Model
{
    use Sortable, CanFollow, CanBeFollowed;

    protected $casts = [
        'notification_on_like' => 'boolean',
	    'notification_on_dislike' => 'boolean',
	    'notification_on_comment' => 'boolean'
    ];
    public function activities()
    {
        return $this->hasManyThrough('App\Models\PostActivity', 'App\Models\Post', 'user_profile_id', 'post_id');
    }

    public function posts()
    {
        return $this->hasMany('App\Models\Post');
    }

    public function followers()
    {
        return $this->hasMany('Overtrue\LaravelFollow\FollowRelation', 'followable_id');
    }

    public function following()
    {
        return $this->hasMany('Overtrue\LaravelFollow\FollowRelation');
    }
}

app/Http/Controllers/Admin/UserProfileController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Auth\Role\Role;
use App\Models\Auth\User\User;
use App\Models\UserProfile;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use Validator;

class UserProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $profiles = UserProfile::sortable(['created_at' => 'desc']);
        if($request->search) {
            $profiles= $profiles->where('name', 'like', '%' . $request->search . '%')
                ->orWhere('user_id', 'like', '%' . $request->search . '%');
        }
        return view('admin.userprofiles.index', ['profiles' => $profiles->paginate()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(UserProfile $profile)
    {
        return view('admin.userprofiles.show', ['profile' => $profile]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(UserProfile $profile)
    {
        return view('admin.userprofiles.edit', ['profile' => $profile]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param User $user
     * @return mixed
     */
    public function update(Request $request, UserProfile $profile)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'gender' => ['required', Rule::in(config('constants.enums.gender'))],
            'user_id' => 'required'
        ]);

        if ($validator->fails()) return redirect()->back()->withErrors($validator->errors());

        $profile->name = $request->get('name');
        $profile->gender = $request->get('gender');
        $profile->user_id = $request->get('user_id');

        $profile->save();

        return redirect()->intended(route('admin.profiles'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(UserProfile $profile)
    {
        $profile->delete();
        return redirect(route('admin.profiles'));
    }
}

app/Http/Controllers/Api/UserProfileController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Requests\PaymentRequest;
use App\Http\Requests\UserProfileRequest;
use App\Models\UserProfile;
use Cartalyst\Stripe\Api\EphemeralKey;
use Cartalyst\Stripe\Laravel\Facades\Stripe;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use League\OAuth1\Client\Server\User;
use App\Http\Controllers\Controller;

class UserProfileController extends Controller
{
    public function store(UserProfileRequest $request)
    {
        $user = Auth::user();
        $profile = UserProfile::where('user_id', $user->id)->first();
        if (!$profile) {
            $profile = new UserProfile();
        }

        $profile->user_id = $user->id;

        if ($request->update == "1") {
            $profile->name = $request->name ? $request->name : $user->name;
            $profile->image = $request->image ? $request->image : $user->image;
            $profile->gender = $request->gender;
            $profile->fcm_registration_id = $request->fcm_registration_id;
            $profile->notification_on_like = $request->notification_on_like;
            $profile->notification_on_dislike = $request->notification_on_dislike;
            $profile->notification_on_comment = $request->notification_on_comment;
        } else {
            $profile->name = $profile->name ? $profile->name : $user->name;
            $profile->email = $profile->email ? $profile->email : $user->email;
            $profile->image = $profile->image ? $profile->image : $user->image;
            $profile->gender = $profile->gender ? $profile->gender : $request->gender;
            $profile->fcm_registration_id = $request->fcm_registration_id; //always give preference to request
            $profile->notification_on_like = $profile->notification_on_like ? $profile->notification_on_like : $request->notification_on_like;
            $profile->notification_on_dislike = $profile->notification_on_dislike ? $profile->notification_on_dislike : $request->notification_on_dislike;
            $profile->notification_on_comment = $profile->notification_on_comment ? $profile->notification_on_comment : $request->notification_on_comment;
        }

        $profile->save();

        /*if($user->email === 'mayur.dhande@mralab.com') {
            $profile->is_admin = 1;
            $profile->save();
        } else {
            $adminProfile = UserProfile::where('is_admin', 1)->first();
            $profile->follow($adminProfile);
        }*/

        $countsQuery = [
            'followers as is_following' => function ($query) use ($profile) {
                $query->where('followables.user_profile_id', $profile->id);
            },
            'following as following_count',
            'followers as followers_count'
        ];
        return response()->json(UserProfile::where('id', $profile->id)->withCount($countsQuery)->firstOrFail());
    }

    public function show(UserProfile $userProfile)
    {
        $user = Auth::user();
        $profile = UserProfile::where('user_id', $user->id)->firstOrFail();

        $countsQuery = [
            'posts as posts_count',
            'activities as like_count' => function ($query) {
                $query->where('post_activities.type', config('constants.POST_ACTIVITY_LIKE'));
            },
            'activities as dislike_count' => function ($query) {
                $query->where('post_activities.type', config('constants.POST_ACTIVITY_DISLIKE'));
            },
            'activities as comment_count' => function ($query) {
                $query->where('post_activities.type', config('constants.POST_ACTIVITY_COMMENT'));
            },
            'followers as is_following' => function ($query) use ($profile) {
                $query->where('followables.user_profile_id', $profile->id);
            },
            'following as following_count',
            'followers as followers_count'
        ];
        return response()->json(UserProfile::where('id', $userProfile->id)->withCount($countsQuery)->firstOrFail());
    }


    public function follow(UserProfile $userProfile)
    {
        $success = 0; // no action
        $user = Auth::user();
        $currentProfile = UserProfile::where('user_id', $user->id)->first();
        if ($currentProfile->isFollowing($userProfile)) {
            $currentProfile->unfollow($userProfile);
            $success = 1; // unfollow
        } else {
            $currentProfile->follow($userProfile);
            $success = 2; // follow
        }
        return response()->json(array("success" => $success));
    }

    public function followers(UserProfile $userProfile)
    {
        $user = Auth::user();
        $profile = UserProfile::where('user_id', $user->id)->firstOrFail();

        $ids = $userProfile->followers()->pluck('user_profile_id')->all();

        $profiles = UserProfile::whereIn('id', $ids);

        $countsQuery = [
            'followers as is_following' => function ($query) use ($profile) {
                $query->where('followables.user_profile_id', $profile->id);
            },
            'following as following_count',
            'followers as followers_count'
        ];


        return response()->json($profiles->withCount($countsQuery)->paginate(config('constants.paginate_per_page')));
        //return response()->json($userProfile->followers()->withCount($countsQuery)->get());
        //return response()->json($userProfile->followers()->get());

    }

    public function following(UserProfile $userProfile)
    {
        $user = Auth::user();
        $profile = UserProfile::where('user_id', $user->id)->firstOrFail();

        $ids = $userProfile->followings()->pluck('id')->all();

        $profiles = UserProfile::whereIn('id', $ids);

        $countsQuery = [
            'followers as is_following' => function ($query) use ($profile) {
                $query->where('followables.user_profile_id', $profile->id);
            },
            'following as following_count',
            'followers as followers_count'
        ];


        return response()->json($profiles->withCount($countsQuery)->paginate(config('constants.paginate_per_page')));

        //return response()->json($userProfile->followings()->get());
    }

    public function activities()
    {
        //$user = Auth::user();
        //$profile = UserProfile::where('user_id', $user->id)->firstOrFail();
        $profile = UserProfile::find(8);

        return response()->json($profile->activities()->orderBy('created_at', 'desc')->paginate(config('constants.paginate_per_page')));
    }

    public function search(Request $request)
    {
        $user = Auth::user();
        $profile = UserProfile::where('user_id', $user->id)->firstOrFail();

        $countsQuery = [
            'followers as is_following' => function ($query) use ($profile) {
                $query->where('followables.user_profile_id', $profile->id);
            },
            'following as following_count',
            'followers as followers_count'
        ];

        $search = $request->search;
        $profiles = UserProfile::where('name', 'like', '%' . $search . '%')->withCount($countsQuery)->paginate(config('constants.paginate_per_page'));
        return response()->json($profiles);
    }

    public function create_payment(PaymentRequest $request)
    {
        $user = Auth::user();
        $profile = UserProfile::where('user_id', $user->id)->firstOrFail();

        try {
            $token = $request->token;
            $charge = Stripe::charges()->create([
                'amount' => 100,
                'currency' => 'usd',
                'description' => 'Registration charge',
                'source' => $token,
            ]);
            $profile->is_paid = true;
            $profile->save();
            return response()->json($charge);
        } catch(\Exception $ex) {
            abort(400);
        }
    }
}

resources/views/admin/userprofiles/edit.blade.php
@extends('admin.layouts.admin')

@section('title', 'Update Profile')

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            {{ Form::open(['route'=>['admin.profiles.update', $profile->id],'method' => 'put','class'=>'form-horizontal form-label-left']) }}

            <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
                    Name
                    <span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <input id="name" type="text"
                           class="form-control col-md-7 col-xs-12 @if($errors->has('name')) parsley-error @endif"
                           name="name" value="{{ $profile->name }}" required>
                    @if($errors->has('name'))
                        <ul class="parsley-errors-list filled">
                            @foreach($errors->get('name') as $error)
                                <li class="parsley-required">{{ $error }}</li>
                            @endforeach
                        </ul>
                    @endif
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="gender">
                    Gender
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <select id="gender" name="gender" class="select2" style="width: 100%" autocomplete="off">
                        <option value="">Select</option>
                        <option {{ $profile->gender == 'm' ? 'selected':'' }} value="m">Male</option>
                        <option {{ $profile->gender == 'f' ? 'selected':'' }} value="f">Female</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="user_id">
                    User ID(Firebase)
                    <span class="required">*</span>
                </label>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <input id="user_id" type="text"
                           class="form-control col-md-7 col-xs-12 @if($errors->has('name')) parsley-error @endif"
                           name="user_id" value="{{ $profile->user_id }}" required>
                    @if($errors->has('user_id'))
                        <ul class="parsley-errors-list filled">
                            @foreach($errors->get('user_id') as $error)
                                <li class="parsley-required">{{ $error }}</li>
                            @endforeach
                        </ul>
                    @endif
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                    <a class="btn btn-primary" href="{{ URL::previous() }}">Cancel</a>
                    <button type="submit" class="btn btn-success"> Save</button>
                </div>
            </div>
            {{ Form::close() }}
        </div>
    </div>
@endsection

@section('styles')
    @parent
    {{ Html::style(mix('assets/admin/css/users/edit.css')) }}
@endsection

@section('scripts')
    @parent
    {{ Html::script(mix('assets/admin/js/users/edit.js')) }}
@endsection

resources/views/admin/userprofiles/index.blade.php
@extends('admin.layouts.admin')

@section('title','User Profiles')

@section('content')
    <div class="row">
        <div class="row">
            <div class="col-sm-4 pull-right">
                {{ Form::open(['route'=>['admin.profiles'],'method' => 'get']) }}
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search Name or User ID" name="search"
                           value="{{ app('request')->input('search') }}">
                      <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Go!</button>
                      </span>
                </div>
                {{ Form::close() }}
            </div>
        </div>
        <table class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0"
               width="100%">
            <thead>
            <tr>
                <th>@sortablelink('name', 'Name', ['page' => $profiles->currentPage()])</th>
		<th>Email</th>
                <th>Gender</th>
                <th>User ID(Firebase)</th>
                <th>Created At</th>
                <th>Update At</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($profiles as $profile)
                <tr>
                    <td>{{ $profile->name }}</td>
		    <td>{{ $profile->email }}</td>
                    <td>{{ $profile->gender }}</td>
                    <td>{{ $profile->user_id }}</td>
                    <td>{{ $profile->created_at }}</td>
                    <td>{{ $profile->updated_at }}</td>
                    <td>
                        <a class="btn btn-xs btn-primary" href="{{ route('admin.profiles.show', [$profile->id]) }}"
                           data-toggle="tooltip" data-placement="top" data-title="View">
                            <i class="fa fa-eye"></i>
                        </a>
                        <a class="btn btn-xs btn-info" href="{{ route('admin.profiles.edit', [$profile->id]) }}"
                           data-toggle="tooltip" data-placement="top" data-title="Edit">
                            <i class="fa fa-pencil"></i>
                        </a>
                        <a class="btn btn-xs btn-danger" href="{{ route('admin.profiles.destroy', [$profile->id]) }}"
                           data-toggle="tooltip" data-placement="top" data-title="Delete">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="pull-right">
            {{ $profiles->links() }}
        </div>
    </div>
@endsection

resources/views/admin/userprofiles/show.blade.php
@extends('admin.layouts.admin')

@section('title', $profile->name . '\'s Profile')

@section('content')
    <div class="row">
        <table class="table table-striped table-hover">
            <tbody>
            <tr>
                <th>Name</th>
                <td>{{ $profile->name }}</td>
            </tr>

	    <tr>
                <th>Email</th>
                <td>{{ $profile->email }}</td>
            </tr>

            <tr>
                <th>Gender</th>
                <td>{{$profile->gender  }}</td>
            </tr>

            <tr>
                <th>User ID(Firebase)</th>
                <td>{{$profile->user_id }}</td>
            </tr>

            <tr>
                <th>Created At</th>
                <td>{{ $profile->created_at }} ({{ $profile->created_at->diffForHumans() }})</td>
            </tr>

            <tr>
                <th>Updated At</th>
                <td>{{ $profile->updated_at }} ({{ $profile->updated_at->diffForHumans() }})</td>
            </tr>
            </tbody>
        </table>
    </div>
    <a class="btn btn-success" href="{{ route('admin.posts', ['user_profile_id' => $profile->id]) }}"
       data-toggle="tooltip" data-placement="top" data-title="Delete">View Posts</a>
    <a class="btn btn-primary" href="{{ URL::previous() }}">Back</a>
@endsection