routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');
});

/**
 * Backend routes
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');

    //Users
    Route::get('users', 'UserController@index')->name('users');
    Route::get('users/{user}', 'UserController@show')->name('users.show');
    //Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::put('users/{user}', 'UserController@update')->name('users.update');
    Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');

    //User Profile
    Route::get('profiles', 'UserProfileController@index')->name('profiles');
    Route::get('profiles/{profile}', 'UserProfileController@show')->name('profiles.show');
    Route::get('profiles/{profile}/edit', 'UserProfileController@edit')->name('profiles.edit');
    Route::put('profiles/{profile}', 'UserProfileController@update')->name('profiles.update');
    Route::get('profiles/{profile}/delete', 'UserProfileController@destroy')->name('profiles.destroy');

    //Posts
    Route::get('posts', 'PostController@index')->name('posts');
    Route::get('posts/{post}', 'PostController@show')->name('posts.show');
    Route::get('posts/{post}/delete', 'PostController@destroy')->name('posts.destroy');

    //Posts Activity
    Route::get('activities', 'PostActivityController@index')->name('postactivities');
    Route::get('activities/{actvity}', 'PostActivityController@show')->name('postactivities.show');
    Route::get('activities/{actvity}/delete', 'PostActivityController@destroy')->name('postactivities.destroy');

    //Comments
    Route::get('comments', 'CommentController@index')->name('comments');
    Route::get('comments/{comment}', 'CommentController@show')->name('comments.show');
    Route::get('comments/{comment}/delete', 'CommentController@destroy')->name('comments.destroy');

    //Comments Activity
    Route::get('comment/activities', 'UserController@index')->name('commentsactivities');

    // Agama
    Route::get('agamas', 'AgamaController@index')->name('agamas');
    Route::get('agamas/{agama}', 'AgamaController@show')->name('agamas.show');
    Route::get('agamas/{agama}/edit', 'AgamaController@edit')->name('agamas.edit');
    Route::put('agamas/{agama}', 'AgamaController@update')->name('agamas.update');
    Route::get('agamas/{agama}/delete', 'AgamaController@destroy')->name('agamas.destroy');
});


Route::get('/', 'Auth\LoginController@showLoginForm');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class Post extends Model
{
    use Sortable;
    public function getUserProfileIdAttribute($value)
    {
        return UserProfile::select(['id', 'name','gender', 'image'])->find($value);
    }

    public function post_activities()
    {
        return $this->hasMany('App\Models\PostActivity');
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Auth\Role\Role;
use App\Models\Auth\User\User;
use App\Models\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use Validator;

class PostController extends Controller
{
    public function index(Request $request)
    {
        $posts = Post::sortable(['name' => 'asc']);
        if($request->user_profile_id) {
            $posts = $posts->where('user_profile_id', $request->user_profile_id);
        }
        return view('admin.posts.index', ['posts' => $posts->paginate()]);
    }

    public function show(Post $post)
    {
        $countsQuery = [
            'post_activities as like_count' => function ($query) {
                $query->where('type', config('constants.POST_ACTIVITY_LIKE'));
            },
            'post_activities as dislike_count' => function ($query) {
                $query->where('type', config('constants.POST_ACTIVITY_DISLIKE'));
            },
            'post_activities as comment_count' => function ($query) {
                $query->where('type', config('constants.POST_ACTIVITY_COMMENT'));
            }
        ];
        return view('admin.posts.show', ['post' => Post::where('id', $post->id)->withCount($countsQuery)->first()]);
    }

    public function destroy(Post $post)
    {
        $post->delete();
        return redirect(route('admin.posts'));
    }
}

app/Http/Controllers/Api/PostController.php
<?php

namespace App\Http\Controllers\Api;

use App\Helpers\PostHelper;
use App\Http\Requests\CreatePostRequest;
use App\Models\Post;
use App\Models\PostActivity;
use App\Models\UserProfile;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
    public function index(Request $request)
    {
        $user = Auth::user();
        $profile = UserProfile::where('user_id', $user->id)->firstOrFail();

        $countsQuery = [
            'post_activities as like_count' => function ($query) {
                $query->where('type', config('constants.POST_ACTIVITY_LIKE'));
            },
            'post_activities as dislike_count' => function ($query) {
                $query->where('type', config('constants.POST_ACTIVITY_DISLIKE'));
            },
            'post_activities as comment_count' => function ($query) {
                $query->where('type', config('constants.POST_ACTIVITY_COMMENT'));
            },
            'post_activities as liked' => function ($query) use ($profile) {
                $query->where('user_profile_id', $profile->id)
                    ->where('type', config('constants.POST_ACTIVITY_LIKE'));
            },
            'post_activities as disliked' => function ($query) use ($profile) {
                $query->where('user_profile_id', $profile->id)
                    ->where('type', config('constants.POST_ACTIVITY_DISLIKE'));
            },
            'post_activities as commented' => function ($query) use ($profile) {
                $query->where('user_profile_id', $profile->id)
                    ->where('type', config('constants.POST_ACTIVITY_COMMENT'));
            }
        ];
        if ($request->treding === "1") {
            $posts = Post::orderBy('created_at', 'desc');
        } else {
            $following = array_merge($profile->followings()->pluck('id')->all(), [$profile->id]);
            $posts = Post::whereIn('user_profile_id', $following)->orderBy('created_at', 'desc');
        }
        if ($request->type) {
            $posts = $posts->where('type', $request->type)->orderBy('created_at', 'desc');
        }
        if ($request->user_profile_id) {
            $posts = $posts->where('user_profile_id', $request->user_profile_id)->orderBy('created_at', 'desc');
        }
        $posts = $posts->where('is_story', false)->withCount($countsQuery)->paginate(config('constants.paginate_per_page'));
        return response()->json($posts);
    }

    public function show(Post $post)
    {
        $user = Auth::user();
        $profile = UserProfile::where('user_id', $user->id)->firstOrFail();

        $countsQuery = [
            'post_activities as like_count' => function ($query) {
                $query->where('type', config('constants.POST_ACTIVITY_LIKE'));
            },
            'post_activities as dislike_count' => function ($query) {
                $query->where('type', config('constants.POST_ACTIVITY_DISLIKE'));
            },
            'post_activities as comment_count' => function ($query) {
                $query->where('type', config('constants.POST_ACTIVITY_COMMENT'));
            },
            'post_activities as liked' => function ($query) use ($profile) {
                $query->where('user_profile_id', $profile->id)
                    ->where('type', config('constants.POST_ACTIVITY_LIKE'));
            },
            'post_activities as disliked' => function ($query) use ($profile) {
                $query->where('user_profile_id', $profile->id)
                    ->where('type', config('constants.POST_ACTIVITY_DISLIKE'));
            },
            'post_activities as commented' => function ($query) use ($profile) {
                $query->where('user_profile_id', $profile->id)
                    ->where('type', config('constants.POST_ACTIVITY_COMMENT'));
            }
        ];
        return response()->json(Post::where('id', $post->id)->where('is_story', false)->withCount($countsQuery)->first());
    }

    public function myposts(Request $request)
    {
        $user = Auth::user();
        $profile = UserProfile::where('user_id', $user->id)->firstOrFail();

        $countsQuery = [
            'post_activities as like_count' => function ($query) {
                $query->where('type', config('constants.POST_ACTIVITY_LIKE'));
            },
            'post_activities as dislike_count' => function ($query) {
                $query->where('type', config('constants.POST_ACTIVITY_DISLIKE'));
            },
            'post_activities as comment_count' => function ($query) {
                $query->where('type', config('constants.POST_ACTIVITY_COMMENT'));
            },
            'post_activities as liked' => function ($query) use ($profile) {
                $query->where('user_profile_id', $profile->id)
                    ->where('type', config('constants.POST_ACTIVITY_LIKE'));
            },
            'post_activities as disliked' => function ($query) use ($profile) {
                $query->where('user_profile_id', $profile->id)
                    ->where('type', config('constants.POST_ACTIVITY_DISLIKE'));
            },
            'post_activities as commented' => function ($query) use ($profile) {
                $query->where('user_profile_id', $profile->id)
                    ->where('type', config('constants.POST_ACTIVITY_COMMENT'));
            }
        ];

        $posts = Post::where('user_profile_id', $profile->id)->where('is_story', false);

        if ($request->type) {
            $posts = $posts->where('type', $request->type);
        }

        $posts = $posts->orderBy('created_at', 'desc')->withCount($countsQuery)->paginate(config('constants.paginate_per_page'));
        return response()->json($posts);
    }

    public function storyUsers()
    {
        $user = Auth::user();
        $profile = UserProfile::where('user_id', $user->id)->firstOrFail();
        $following = array_merge($profile->followings()->pluck('id')->all(), [$profile->id]);
        $users = Post::whereIn('user_profile_id', $following)->where('is_story', true)->get()->pluck('user_profile_id')->all();
        $userIds = [];
        foreach ($users as $user) {
            $userIds[] = $user->id;
        }
        return response()->json(UserProfile::whereIn('id', $userIds)->get());
    }

    public function stories(UserProfile $userProfile)
    {
        $posts = Post::where('user_profile_id', $userProfile->id)->where('is_story', true)
            ->orderBy('created_at', 'desc')->get();
        return response()->json($posts);
    }

    public function like(Post $post)
    {
        $status = $this->likeDislikePost($post, config('constants.POST_ACTIVITY_LIKE'));
        return response()->json(array("id" => $post->id, "status" => $status), 200);
    }

    private function likeDislikePost($post, $type)
    {
        $user = Auth::user();
        $profile = UserProfile::where('user_id', $user->id)->firstOrFail();

        $previousActivity = PostActivity::where('user_profile_id', $profile->id)
            ->where('post_id', $post->id)
            ->whereIn('type', array(config('constants.POST_ACTIVITY_LIKE'), config('constants.POST_ACTIVITY_DISLIKE')))
            ->first();

        if ($previousActivity) {
            $previousActivity->delete();

            if ($previousActivity->type == $type) {
                return -1; // unlike or undislike
            }
        }

        PostHelper::createPostActivity($profile, $post->id, $type);
        return 1; // like or dislike
    }

    public function dislike(Post $post)
    {
        $status = $this->likeDislikePost($post, config('constants.POST_ACTIVITY_DISLIKE'));

        return response()->json(array("id" => $post->id, "status" => $status), 200);
    }

    public function share(Post $post)
    {
        $post->share_count = $post->share_count + 1;
        $post->save();
        return response()->json(null, 200);
    }

    public function store(CreatePostRequest $request)
    {
        $user = Auth::user();
        $profile = UserProfile::where('user_id', $user->id)->first();
        $post = new Post();
        $post->title = $request->title;
        $post->text = $request->text;
        $post->media_url = $request->media_url;
        $post->type = $request->type;
        $post->user_profile_id = $profile->id;
        $post->video_thumbnail_url = $request->video_thumbnail_url;
        $post->is_story = $request->is_story ? true : false;
        $post->save();

        return response()->json(Post::find($post->id));
    }

    public function destroy(Post $post)
    {
        $deleted = $post->delete();
        $status = $deleted ? 200 : 400;
        return response()->json(null, $status);
    }
}

resources/views/admin/posts/index.blade.php
@extends('admin.layouts.admin')

@section('title','Posts')

@section('content')
    <div class="row">
        <table class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0"
               width="100%">
            <thead>
            <tr>
                <th>Post Type</th>
                <th>Posted By</th>
                <th>Created At</th>
                <th>Update At</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($posts as $post)
                <tr>
                    <td>{{ $post->type }}</td>
                    <td><a href="{{ route('admin.profiles.show', [$post->user_profile_id->id]  ) }}">{{ $post->user_profile_id->name }}</a></td>
                    <td>{{ $post->created_at }}</td>
                    <td>{{ $post->updated_at }}</td>
                    <td>
                        <a class="btn btn-xs btn-primary" href="{{ route('admin.posts.show', [$post->id]) }}"
                           data-toggle="tooltip" data-placement="top" data-title="View">
                            <i class="fa fa-eye"></i>
                        </a>
                        <a class="btn btn-xs btn-danger" href="{{ route('admin.posts.destroy', [$post->id]) }}"
                           data-toggle="tooltip" data-placement="top" data-title="Delete">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="pull-right">
            {{ $posts->links() }}
        </div>
    </div>
@endsection

resources/views/admin/posts/show.blade.php
@extends('admin.layouts.admin')

@section('title', 'Post')

@section('content')
    <div class="row">
        <table class="table table-striped table-hover">
            <tbody>
            <tr>
                <th>ID</th>
                <td>{{ $post->id }}</td>
            </tr>

            <tr>
                <th>Type</th>
                <td>{{ $post->type }}</td>
            </tr>

            <tr>
                <th>User</th>
                <td><a href="{{ route('admin.posts.show', [$post->user_profile_id->id]  ) }}">{{ $post->user_profile_id->name }}</a></td>
            </tr>

            <tr>
                <th>Text</th>
                <td>{{ $post->text }}</td>
            </tr>

            <tr>
                <th>Media Url</th>
                <td><a target="_blank" href="{{ $post->media_url }}">{{ $post->media_url }}</a></td>
            </tr>

            <tr>
                <th>Like Count</th>
                <td>{{ $post->like_count }}</td>
            </tr>

            <tr>
                <th>Dislike Count</th>
                <td>{{ $post->dislike_count }}</td>
            </tr>

            <tr>
                <th>Comment Count</th>
                <td>{{ $post->comment_count }}</td>
            </tr>

            <tr>
                <th>Created At</th>
                <td>{{ $post->created_at }} ({{ $post->created_at->diffForHumans() }})</td>
            </tr>

            <tr>
                <th>Updated At</th>
                <td>{{ $post->updated_at }} ({{ $post->updated_at->diffForHumans() }})</td>
            </tr>
            </tbody>
        </table>
    </div>
    <a class="btn btn-danger" href="{{ route('admin.posts.destroy', [$post->id]) }}"
       data-toggle="tooltip" data-placement="top" data-title="Delete">Delete</a>
    <a class="btn btn-success" href="{{ route('admin.postactivities', ["post_id" => $post->id]) }}"
       data-toggle="tooltip" data-placement="top" data-title="Delete">View Activities</a>
    <a class="btn btn-success" href="{{ route('admin.comments', ["post_id" => $post->id]) }}"
       data-toggle="tooltip" data-placement="top" data-title="Delete">View Comments</a>
    <a class="btn btn-primary" href="{{ URL::previous() }}">Back</a>
@endsection